parameters:
#    diego_core.example.class: Diego\CoreBundle\Example

services:
#    diego_core.example:
#        class: %diego_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
